// CNTXT.H

// Listing 06-11


#define RS_ALL          300
#define RS_ICON         RS_ALL
#define RS_MENU         RS_ALL
#define RS_ACCELTABLE   RS_ALL
#define RS_TBMENU       350

#define ST_CLASSNAME    10
#define ST_WINDOWTITLE  11

#define MN_FILE 99
// Defines for MN_FILE menu
#define MN_NEW  100
#define MN_OPEN 101
#define MN_SAVE 102
#define MN_SAVEAS 103
#define MN_EXIT 104

#define MN_EDIT 200
// Defines for MN_EDIT menu
#define MN_UNDO 201
#define MN_CUT  202
#define MN_COPY 203
#define MN_PASTE 204
#define MN_CLEAR 205

#define MN_HELP 300
#define MN_PRODINFO 301


// window context menu
#define PM_OPEN         500
#define PM_HELP         501
#define PM_CREATEAN     502
#define PM_COPY         503
#define PM_MOVE         504
#define PM_SHADOW       505
#define PM_DELETE       506


#define MN_SETTINGS     600
#define MN_ICONVIEW     601
#define MN_HELP1        602
#define MN_HELP2        603
#define MN_HELP3        604
#define MN_HELP4        605
#define MN_DEFAULT      606
#define MN_EDITOR       607
#define MN_REDO         608
#define MN_DELETE       609
#define MN_FIND         610
#define MN_SELECTALL    611
#define MN_DESELECTALL  612
#define MN_WINDOW       613


