// SYSDLLS.H
// Listing 10-08


#define RS_ALL          300
#define RS_ICON         RS_ALL
#define RS_MENU         RS_ALL
#define RS_ACCELTABLE   RS_ALL

// window IDs
#define CT_ADD      500
#define CT_REMOVE   501
#define CT_STATIC   502
#define CT_KEY      503
#define CT_LIST     504
#define CT_ACTION   505

#define WIDTH       480
#define HEIGHT      260



// STRINGTABLE
#define ST_CLASSNAME    400
#define ST_WINDOWTITLE  401

