// PANEL.H
// Listing 12-03

#define RS_ALL          300
#define RS_ICON         RS_ALL
#define RS_MENU         RS_ALL
#define RS_ACCELTABLE   RS_ALL
#define RS_BITMAP       RS_ALL


// application menu
#define MN_EXIT         100
#define MN_PRODINFO     101

// listbox menu
#define RS_LISTMENU     350
#define MN_EMPTY        351
#define MN_TEXT         352


// STRINGTABLE IDs
#define ST_CLASSNAME    1000
#define ST_WINDOWTITLE  1001

