// ACCEL.H

// Listing 06-10


#define RS_ALL          300
#define RS_ICON         RS_ALL
#define RS_MENU         RS_ALL
#define RS_ACCELTABLE   RS_ALL

#define ST_CLASSNAME    10
#define ST_WINDOWTITLE  11

#define MN_FILE 99
// Defines for MN_FILE menu
#define MN_NEW  100
#define MN_OPEN 101
#define MN_SAVE 102
#define MN_SAVEAS 103
#define MN_EXIT 104

#define MN_EDIT 200
// Defines for MN_EDIT menu
#define MN_UNDO 201
#define MN_CUT  202
#define MN_COPY 203
#define MN_PASTE 204
#define MN_CLEAR 205

#define MN_HELP 300
#define MN_PRODINFO 301
#define MN_HELP1        602
#define MN_HELP2        603
#define MN_HELP3        604
#define MN_HELP4        605
#define MN_REDO         606
#define MN_DELETE       607
#define MN_FIND         608
#define MN_SELECTALL    609
#define MN_DESELECTALL  610

#define RS_SECOND       500
#define MN_BACK         501

