// CLIPSHOW.H
// Listing 11-02

#define RS_ALL          300
#define RS_ICON         RS_ALL
#define RS_MENU         RS_ALL
#define RS_ACCELTABLE   RS_ALL
#define RS_TBMENU       350

#define ST_CLASSNAME    10
#define ST_WINDOWTITLE  11

#define MN_FILE 99
// Defines for MN_FILE menu
#define MN_NEW  100
#define MN_OPEN 101
#define MN_SAVE 102
#define MN_SAVEAS 103
#define MN_EXIT 104

#define MN_EDIT         200
// Defines for MN_EDIT menu
#define MN_UNDO         201
#define MN_CUT          202
#define MN_COPY         203
#define MN_PASTE        204
#define MN_CLEAR        205
#define MN_REDO         206
#define MN_DELETE       207
#define MN_SELECTALL    208
#define MN_DESELECTALL  209
#define MN_FIND         210



#define MN_HELP         300
// Defines for MN_HELP menu
#define MN_HELP1        301
#define MN_HELP2        302
#define MN_HELP3        303
#define MN_HELP4        304
#define MN_PRODINFO     305



