// DIALOGS.H

// Notebook Settings
#define CT_CLRPAL       200
#define CT_FNTPAL       201
#define CT_TEXTEX       202
#define CT_BACKEX       203

#define CT_UNDO         300
#define CT_DEFAULT      301
#define CT_HELP         302

// Notebook values
#define CT_POSITION      401
#define CT_LINENUMBER    402
#define CT_INFOLINE      403
#define CT_SENDIT        404


// SearchBox
#define DL_SEARCH        310
#define DL_REPLACE       311
#define DL_CASE          312
#define DL_UP            313
#define DL_DOWN          314

// GotoBox
#define DL_GOTO          315
#define DL_LINE          316
#define DL_VSCROLL       317
