// FLOW.H
// Listing 07-06

#define RS_ALL          300
#define RS_ICON         RS_ALL
#define RS_MENU         RS_ALL
#define RS_ACCELTABLE   RS_ALL

#define TM_WINDOW       400


#define MN_FILE 99
// Defines for MN_FILE menu
#define MN_DIALOG   100
#define MN_WINDOW   101
#define MN_EXIT     102

#define ST_CLASSNAME   10000
#define ST_TESTCLASS   10001
#define ST_WINDOWTITLE   10002
#define ST_TESTTITLE   10003

